window.SLOW_UPLOAD_OPTIONS = {
  countries: Array.isArray(window.SLOW_COUNTRIES) && window.SLOW_COUNTRIES.length
    ? window.SLOW_COUNTRIES
    : ["Sierra Leone", "Ethiopia", "Pakistan", "Kenya", "Bangladesh", "Timor-Leste", "Solomon Islands"],
  mainCategories: ["Group Loans", "Individual Loans", "Savings", "Payments", "Insurance", "Savings Groups", "Currency"],
  crossCuttingCategories: ["Icons", "Templates", "Frames", "Digital", "Paper", "Documents - Manuals", "Documents - Research"],
  productDetails: ["Group", "Individual", "Agent", "Farmer", "Women", "Youth"],
  institutions: ["Harvest Microfinance", "BRAC", "World Vision", "CARE", "UNCDF", "Community NGO"],
  types: ["Icon", "Template", "Frame", "Digital", "Paper", "Document"],
  sampleResources: [
    {
      id: "sample_1",
      title: "Savings icon card",
      description: "Picture card for talking about savings.",
      country: "Sierra Leone",
      category: "Savings",
      type: "Icon",
      keywords: ["savings", "icon"],
      productDetail: "Group",
      crossCutting: "Icons",
      institution: "BRAC",
      created_at: "2026-04-01T00:00:00.000Z",
    },
    {
      id: "sample_2",
      title: "Group loan frame",
      description: "Simple frame for group loan discussion.",
      country: "Sierra Leone",
      category: "Group Loans",
      type: "Frame",
      keywords: ["group", "loan", "frame"],
      productDetail: "Group",
      crossCutting: "Frames",
      institution: "World Vision",
      created_at: "2026-04-02T00:00:00.000Z",
    },
    {
      id: "sample_currency_1",
      title: "Currency icon card",
      description: "Picture icon for recognizing notes and coins during training.",
      country: "Ethiopia",
      category: "Currency",
      type: "Icon",
      keywords: ["currency", "icon", "birr", "money"],
      productDetail: "Individual",
      crossCutting: "Icons",
      institution: "BRAC",
      created_at: "2026-04-02T00:00:00.000Z",
    },
    {
      id: "sample_currency_2",
      title: "Currency frame practice sheet",
      description: "Frame for writing local currency amounts in visual learning sessions.",
      country: "Ethiopia",
      category: "Currency",
      type: "Frame",
      keywords: ["currency", "frame", "money", "cash"],
      productDetail: "Group",
      crossCutting: "Frames",
      institution: "World Vision",
      created_at: "2026-04-03T00:00:00.000Z",
    },
    {
      id: "sample_3",
      title: "Payment poster",
      description: "Visual poster for payment steps.",
      country: "Pakistan",
      category: "Payments",
      type: "Template",
      keywords: ["payment", "poster"],
      productDetail: "Agent",
      crossCutting: "Paper",
      institution: "CARE",
      created_at: "2026-04-03T00:00:00.000Z",
    },
    {
      id: "sample_4",
      title: "Insurance picture guide",
      description: "Simple image guide for insurance topics.",
      country: "Bangladesh",
      category: "Insurance",
      type: "Document",
      keywords: ["insurance", "guide"],
      productDetail: "Individual",
      crossCutting: "Documents - Manuals",
      institution: "UNCDF",
      created_at: "2026-04-04T00:00:00.000Z",
    },
    {
      id: "sample_5",
      title: "Savings group template",
      description: "Template for savings group meetings.",
      country: "Sierra Leone",
      category: "Savings Groups",
      type: "Template",
      keywords: ["meeting", "template"],
      productDetail: "Women",
      crossCutting: "Templates",
      institution: "Plan",
      created_at: "2026-04-05T00:00:00.000Z",
    },
    {
      id: "sample_6",
      title: "Research picture sheet",
      description: "Image-first research sheet.",
      country: "Kenya",
      category: "Individual Loans",
      type: "Document",
      keywords: ["research", "picture"],
      productDetail: "Youth",
      crossCutting: "Documents - Research",
      institution: "Community NGO",
      created_at: "2026-04-06T00:00:00.000Z",
    },
    {
      id: "sample_7",
      title: "Digital icon sheet",
      description: "Picture sheet for digital service training.",
      country: "East Timor",
      category: "Payments",
      type: "Digital",
      keywords: ["digital", "service"],
      productDetail: "Agent",
      crossCutting: "Digital",
      institution: "Harvest Microfinance",
      created_at: "2026-04-07T00:00:00.000Z",
    },
    {
      id: "sample_8",
      title: "Paper manual page",
      description: "Paper-first OIM manual page for field staff.",
      country: "Solomon Islands",
      category: "Savings",
      type: "Paper",
      keywords: ["manual", "paper"],
      productDetail: "Group",
      crossCutting: "Documents - Manuals",
      institution: "UNCDF",
      created_at: "2026-04-08T00:00:00.000Z",
    },
  ],
};
